[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
disallow_untyped_defs = True
no_implicit_optional = True
plugins = pydantic.mypy
mypy_path = services/common/src,services/ingestion/src
explicit_package_bases = True

[mypy-services.common.tests.*]
disallow_untyped_defs = False

[mypy-services.ingestion.tests.*]
disallow_untyped_defs = False

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-betfairlightweight.*]
ignore_missing_imports = True
