"""Strategy validation orchestration and artifact writer."""

from __future__ import annotations

import argparse
import json
import re
import uuid
from dataclasses import asdict, dataclass
from datetime import UTC, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml
from algobet_common.schemas import MarketData, Venue
from jinja2 import Template

from backtest_engine.metrics import compute_all_metrics, compute_max_drawdown, compute_sharpe
from backtest_engine.param_sweep import param_grid, run_sweep
from backtest_engine.promotion_gate import check_promotion_criteria, load_thresholds
from backtest_engine.regimes import label_vol_regime, regime_conditional_metrics
from backtest_engine.significance import (
    bootstrap_sharpe_ci,
    compare_to_random_baseline,
    t_test_vs_zero,
)
from backtest_engine.strategies import mean_reversion
from backtest_engine.walkforward import (
    generate_splits,
    run_strategy_backtest,
    summarise_walkforward,
    walkforward_run,
)

_REPORT_TEMPLATE = Template(
    """Generated by backtest_engine.validate at {{ run_ts }}. """
    """Numbers in this report are produced by deterministic scripts.

# Backtest: {{ strategy_slug }}

- **Run ID:** {{ run_id }}
- **Data source:** {{ data_source }}
- **Trades (closed):** {{ n_trades }}

## Metrics

{% for k, v in metrics.items() %}
- **{{ k }}:** {{ v }}
{% endfor %}

## Significance

{% for k, v in significance.items() %}
- **{{ k }}:** {{ v }}
{% endfor %}

## Walk-forward summary

{% for k, v in walkforward.items() %}
- **{{ k }}:** {{ v }}
{% endfor %}

## Regime metrics

{% for k, v in regime_metrics.items() %}
- **{{ k }}:** {{ v }}
{% endfor %}

## Promotion

- **Pass:** {{ promotion_pass }}
{% if failure_reasons %}
- **Failure reasons:**
{% for r in failure_reasons %}
  - {{ r }}
{% endfor %}
{% endif %}
"""
)


@dataclass(frozen=True)
class BacktestReport:
    strategy_slug: str
    run_id: str
    run_ts: datetime
    data_source: str
    n_trades: int
    metrics: dict[str, Any]
    significance: dict[str, Any]
    walkforward: dict[str, Any]
    param_sweep_path: str | None
    regime_metrics: dict[str, Any]
    promotion_pass: bool
    failure_reasons: list[str]


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _parse_wiki_parameters(strategy_slug: str) -> dict[str, Any]:
    path = _repo_root() / "wiki" / "30-Strategies" / f"{strategy_slug}.md"
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        msg = f"no frontmatter in {path}"
        raise ValueError(msg)
    fm = yaml.safe_load(m.group(1)) or {}
    params = fm.get("parameters")
    if not isinstance(params, dict):
        msg = "wiki frontmatter 'parameters' must be a mapping"
        raise ValueError(msg)
    return dict(params)


def synthetic_polymarket_ticks(
    n: int,
    *,
    seed: int,
    market_id: str = "synthetic.pm",
) -> list[MarketData]:
    """Random-walk mid at 1 s cadence, shaped as Polymarket ``MarketData``."""
    rng = np.random.default_rng(seed)
    base = datetime(2026, 1, 1, 0, 0, 0, tzinfo=UTC)
    steps = rng.normal(0.0, 0.002, size=n)
    raw_mid = 0.5 + np.cumsum(steps)
    mid = np.clip(raw_mid, 0.02, 0.98)
    spread = 0.01
    ticks: list[MarketData] = []
    for i in range(n):
        m = Decimal(str(round(float(mid[i]), 6)))
        sp = Decimal(str(spread))
        ticks.append(
            MarketData(
                venue=Venue.POLYMARKET,
                market_id=market_id,
                timestamp=base + timedelta(seconds=i),
                bids=[(m - sp / 2, Decimal("10"))],
                asks=[(m + sp / 2, Decimal("10"))],
            )
        )
    return ticks


def validate_strategy(
    strategy_slug: str,
    data_source: str = "synthetic",
    n_synthetic_ticks: int = 5_000,
    param_sweep: bool = True,
    walkforward_splits: int = 5,
    **config: Any,
) -> BacktestReport:
    """Full validation pipeline; ``config`` may include ``seed`` (int)."""
    seed = int(config.get("seed", 42))
    if data_source != "synthetic":
        msg = "only data_source='synthetic' is implemented in this delivery"
        raise ValueError(msg)

    params = _parse_wiki_parameters(strategy_slug)
    params = {**params, "venue": str(params.get("venue", "polymarket"))}
    ticks = synthetic_polymarket_ticks(n_synthetic_ticks, seed=seed)

    metrics_h, trades, equity = run_strategy_backtest(mean_reversion.on_tick, ticks, params)

    if len(trades) < 2:
        bar_rets = np.diff(equity) / np.where(equity[:-1] != 0, equity[:-1], 1.0)
        all_metrics: dict[str, Any] = {
            "sharpe": float(compute_sharpe(bar_rets, ann_factor=252.0)),
            "sortino": 0.0,
            "max_drawdown": compute_max_drawdown(equity),
            "calmar": 0.0,
            "hit_rate": 0.0,
            "win_rate": 0.0,
            "profit_factor": 0.0,
            "expectancy": 0.0,
            "avg_trade": 0.0,
            "n_trades": 0,
            "harness_sharpe": metrics_h["sharpe"],
            "total_pnl_gbp": float(metrics_h["total_pnl_gbp"]),
        }
    else:
        all_metrics = compute_all_metrics(trades, equity, ann_factor=252.0)
        all_metrics["harness_sharpe"] = metrics_h["sharpe"]
        all_metrics["total_pnl_gbp"] = float(metrics_h["total_pnl_gbp"])

    bar_rets = np.diff(equity) / np.where(equity[:-1] != 0, equity[:-1], 1.0)
    rng_sig = np.random.default_rng(seed)
    sharpe_lo, sharpe_hi = bootstrap_sharpe_ci(bar_rets, n_bootstrap=2000, alpha=0.05, rng=rng_sig)
    tt = t_test_vs_zero(bar_rets)
    mid_series = pd.Series(
        [float((t.bids[0][0] + t.asks[0][0]) / 2) for t in ticks],
        index=[t.timestamp.replace(tzinfo=None) for t in ticks],
    )
    significance: dict[str, Any] = {
        "sharpe_ci_lo": sharpe_lo,
        "sharpe_ci_hi": sharpe_hi,
        "t_test": tt,
    }
    if len(trades) >= 2:
        null_rng = np.random.default_rng(seed + 1)
        significance["random_baseline"] = compare_to_random_baseline(
            trades,
            n_simulations=500,
            reference_returns=mid_series.values,
            rng=null_rng,
        )

    n = len(ticks)
    train_bars = max(200, n // (walkforward_splits + 2))
    test_bars = max(50, n // (walkforward_splits + 4))
    splits = generate_splits(n, train_bars, test_bars)[:walkforward_splits]
    wf_results = [
        walkforward_run(mean_reversion.on_tick, ticks, sp, params, fit_fn=None) for sp in splits
    ]
    walkforward = summarise_walkforward(wf_results)

    run_id_cfg = config.get("run_id")
    run_id = str(run_id_cfg) if run_id_cfg is not None else str(uuid.uuid4())
    run_ts_cfg = config.get("run_ts")
    run_ts = run_ts_cfg if isinstance(run_ts_cfg, datetime) else datetime.now(UTC)
    ts_slug = run_ts.strftime("%Y-%m-%d-%H%M%S")
    art_dir = _repo_root() / "artifacts" / "backtests" / strategy_slug / ts_slug
    art_dir.mkdir(parents=True, exist_ok=True)

    sweep_rel: str | None = None
    if param_sweep:
        ws = int(params.get("window_size", 10))
        zt = float(params.get("z_threshold", 1.0))
        grid = param_grid(
            {
                "window_size": [max(5, ws - 2), ws, ws + 2],
                "z_threshold": [max(0.5, zt - 0.3), zt, zt + 0.3],
                "stake_gbp": [str(params.get("stake_gbp", "1.0"))],
                "min_stddev": [float(params.get("min_stddev", 0.0001))],
                "venue": [str(params.get("venue", "polymarket"))],
            }
        )
        df = run_sweep(mean_reversion.on_tick, ticks, grid, metric="sharpe")
        sweep_path = art_dir / "param_sweep.csv"
        df.to_csv(sweep_path, index=False)
        sweep_rel = str(sweep_path.relative_to(_repo_root() / "artifacts"))
    wf_csv = art_dir / "walkforward.csv"
    pd.DataFrame(
        [
            {
                **{"split": i},
                **r["in_sample"],
                **{f"oos_{k}": v for k, v in r["out_of_sample"].items()},
            }
            for i, r in enumerate(wf_results)
        ]
    ).to_csv(wf_csv, index=False)

    vol_reg = label_vol_regime(mid_series, window=30, quantile_high=0.75)

    def _mean_pnl(ts: list[dict[str, Any]]) -> float:
        return float(np.mean([x["pnl"] for x in ts])) if ts else 0.0

    regime_metrics = regime_conditional_metrics(trades, vol_reg, _mean_pnl)
    (art_dir / "regimes.json").write_text(json.dumps(regime_metrics, indent=2), encoding="utf-8")

    thresholds = load_thresholds(strategy_slug)
    report_pre = BacktestReport(
        strategy_slug=strategy_slug,
        run_id=run_id,
        run_ts=run_ts,
        data_source=data_source,
        n_trades=len(trades),
        metrics=all_metrics,
        significance=significance,
        walkforward=walkforward,
        param_sweep_path=sweep_rel,
        regime_metrics=regime_metrics,
        promotion_pass=False,
        failure_reasons=[],
    )
    ok, reasons = check_promotion_criteria(report_pre, thresholds)
    report = BacktestReport(
        strategy_slug=strategy_slug,
        run_id=run_id,
        run_ts=run_ts,
        data_source=data_source,
        n_trades=len(trades),
        metrics=all_metrics,
        significance=significance,
        walkforward=walkforward,
        param_sweep_path=sweep_rel,
        regime_metrics=regime_metrics,
        promotion_pass=ok,
        failure_reasons=reasons,
    )

    serialisable = asdict(report)
    serialisable["run_ts"] = report.run_ts.isoformat()
    metrics_json = json.dumps(serialisable, indent=2, default=str)
    (art_dir / "metrics.json").write_text(metrics_json, encoding="utf-8")
    (art_dir / "report.json").write_text(metrics_json, encoding="utf-8")

    md = _REPORT_TEMPLATE.render(
        run_ts=report.run_ts.isoformat(),
        strategy_slug=report.strategy_slug,
        run_id=report.run_id,
        data_source=report.data_source,
        n_trades=report.n_trades,
        metrics=report.metrics,
        significance=report.significance,
        walkforward=report.walkforward,
        regime_metrics=report.regime_metrics,
        promotion_pass=report.promotion_pass,
        failure_reasons=report.failure_reasons,
    )
    (art_dir / "report.md").write_text(md, encoding="utf-8")

    return report


def main() -> int:
    p = argparse.ArgumentParser(description="Run deterministic strategy validation")
    p.add_argument("--strategy", required=True, help="strategy slug (wiki filename stem)")
    p.add_argument("--synthetic", action="store_true", help="use synthetic tick generator")
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()
    if not args.synthetic:
        print("only --synthetic is supported", file=__import__("sys").stderr)
        return 2
    validate_strategy(args.strategy, data_source="synthetic", seed=args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
