"""Tests for validate orchestrator."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pytest
from backtest_engine import validate as validate_mod


def _minimal_wiki(tmp: Path) -> None:
    p = tmp / "wiki" / "30-Strategies" / "polymarket-yes-mean-revert.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        "---\n"
        "title: Test\n"
        "type: strategy\n"
        "parameters:\n"
        "  window_size: 15\n"
        "  z_threshold: 1.2\n"
        '  stake_gbp: "1.0"\n'
        "  min_stddev: 0.0001\n"
        "  venue: polymarket\n"
        "---\n\n# Body\n",
        encoding="utf-8",
    )


def test_validate_end_to_end_artifacts(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    _minimal_wiki(tmp_path)
    monkeypatch.setattr(validate_mod, "_repo_root", lambda: tmp_path)

    validate_mod.validate_strategy(
        "polymarket-yes-mean-revert",
        data_source="synthetic",
        n_synthetic_ticks=800,
        param_sweep=True,
        walkforward_splits=3,
        seed=7,
    )

    art = tmp_path / "artifacts" / "backtests" / "polymarket-yes-mean-revert"
    dirs = list(art.iterdir())
    assert len(dirs) == 1
    d = dirs[0]
    assert (d / "metrics.json").is_file()
    assert (d / "report.md").is_file()
    assert (d / "walkforward.csv").is_file()
    assert (d / "param_sweep.csv").is_file()
    assert (d / "regimes.json").is_file()
    first = (d / "report.md").read_text(encoding="utf-8").splitlines()[0]
    assert first.startswith("Generated by backtest_engine.validate at")


def test_deterministic_numeric_outputs(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    _minimal_wiki(tmp_path)
    monkeypatch.setattr(validate_mod, "_repo_root", lambda: tmp_path)

    a = validate_mod.validate_strategy(
        "polymarket-yes-mean-revert",
        n_synthetic_ticks=600,
        param_sweep=False,
        walkforward_splits=2,
        seed=99,
    )
    b = validate_mod.validate_strategy(
        "polymarket-yes-mean-revert",
        n_synthetic_ticks=600,
        param_sweep=False,
        walkforward_splits=2,
        seed=99,
    )
    for key in ("sharpe", "hit_rate", "expectancy"):
        assert np.isclose(float(a.metrics[key]), float(b.metrics[key]))


def test_byte_identical_artifacts_with_pinned_run_metadata(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Per plan: same seed + pinned run_id/run_ts → byte-identical metrics.json."""
    _minimal_wiki(tmp_path)
    monkeypatch.setattr(validate_mod, "_repo_root", lambda: tmp_path)
    pinned_run_id = "00000000-0000-0000-0000-000000000001"
    pinned_run_ts = datetime(2026, 4, 24, 12, 0, 0, tzinfo=UTC)

    def run_once(subdir: str) -> bytes:
        monkeypatch.setattr(
            validate_mod,
            "_repo_root",
            lambda: tmp_path / subdir,
        )
        validate_mod.validate_strategy(
            "polymarket-yes-mean-revert",
            n_synthetic_ticks=500,
            param_sweep=False,
            walkforward_splits=2,
            seed=123,
            run_id=pinned_run_id,
            run_ts=pinned_run_ts,
        )
        art = tmp_path / subdir / "artifacts" / "backtests" / "polymarket-yes-mean-revert"
        return next(art.iterdir()).joinpath("metrics.json").read_bytes()

    # need the wiki in both subdirs because _repo_root is swapped per call
    src_wiki = (tmp_path / "wiki" / "30-Strategies" / "polymarket-yes-mean-revert.md").read_text(
        encoding="utf-8"
    )
    for sub in ("run_a", "run_b"):
        wiki = tmp_path / sub / "wiki" / "30-Strategies" / "polymarket-yes-mean-revert.md"
        wiki.parent.mkdir(parents=True, exist_ok=True)
        wiki.write_text(src_wiki, encoding="utf-8")

    assert run_once("run_a") == run_once("run_b")


def test_run_id_is_uuid(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    _minimal_wiki(tmp_path)
    monkeypatch.setattr(validate_mod, "_repo_root", lambda: tmp_path)
    rep = validate_mod.validate_strategy(
        "polymarket-yes-mean-revert",
        n_synthetic_ticks=400,
        seed=1,
    )
    uuid.UUID(rep.run_id)
